# Generated by Django 4.0.4 on 2022-05-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=200)),
                ('deck', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
                ('polish', models.CharField(max_length=200)),
                ('publication_date', models.IntegerField()),
                ('due_date', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('answers', models.CharField(max_length=200)),
                ('card_opening_times', models.CharField(max_length=200)),
                ('card_closing_times', models.CharField(max_length=200)),
                ('durations', models.CharField(max_length=200)),
                ('card_revision_days', models.CharField(max_length=200)),
                ('line', models.IntegerField()),
            ],
        ),
    ]
