# Generated by Django 4.0.4 on 2022-05-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='reviews_limit',
            new_name='daily_limit_of_new_cards',
        ),
    ]
